#!/bin/bash

MAJOR=$1
MINOR=$2
VERS="${MAJOR}.${MINOR}.0"
FILEVERS="${MAJOR}_${MINOR}"

cppo -D "MAJOR_VERSION ${MAJOR}" -D "MINOR_VERSION ${MINOR}" foo.ml > gen/foo-${FILEVERS}.ml
../tools/LAUNCH not-ocamlfind preprocess  -package unix,compiler-libs.common,camlp5.quotations,camlp5.extfun,rresult,fmt,pa_ppx_utils,pa_ppx_runtime,compiler-libs.common,camlp5.macro,camlp5.pr_r,pa_ppx_import,pa_ppx_deriving_plugins.std \
-syntax camlp5o -ppopt -D -ppopt BOOTSTRAP \
-ppopt -pa_import-I -ppopt . \
-ppopt -pa_import-I -ppopt /home/chet/Hack/Ocaml/GENERIC/${VERS}/lib/ocaml \
-ppopt -pa_import-I -ppopt /home/chet/Hack/Ocaml/GENERIC/${VERS}/lib/ocaml/compiler-libs \
-ppopt -pa_import-I -ppopt /home/chet/Hack/Ocaml/GENERIC/${VERS}/.opam-switch/sources/ocaml-base-compiler.${VERS}/stdlib \
-ppopt -pa_import-I -ppopt /home/chet/Hack/Ocaml/GENERIC/${VERS}/.opam-switch/sources/ocaml-base-compiler.${VERS}/parsing \
-ppopt -pa_import-I -ppopt /home/chet/Hack/Ocaml/GENERIC/${VERS}/.opam-switch/sources/ocaml-base-compiler.${VERS}/typing \
-ppopt -sep -ppopt "\n" \
-ppopt -pa_import-mli-only \
-ppopt -pa_import-redeclare \
gen/foo-${FILEVERS}.ml > gen/ast_${FILEVERS}.ml

